package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gorilla/mux"

	chttp "github.com/CLesnar/go/internal/pkg/http"
	"github.com/CLesnar/go/internal/pkg/util"
	"github.com/CLesnar/go/pkg/weather"
)

type WeatherConditionParameters struct {
	Latitude  *float64 `json:"lat,omitempty"`   // latitude of location on earth to get weather data for
	Longitude *float64 `json:"lon,omitempty"`   // longitude of location on earth to get weather data for
	ApiId     *string  `json:"appid,omitempty"` // OpenWeatherMap API ID/Key generated by signing up to use their APIs
}

type WeatherWebAppScope struct {
}

var (
	controller = &WeatherWebAppScope{}
)

func (c *WeatherWebAppScope) Route(r *mux.Router) {
	s := r.PathPrefix("/v1/weather").Subrouter()
	s.HandleFunc("/data", controller.GetWeatherDataHandler).Methods(http.MethodGet)
	// Add middleware specific to this controller
}

func (p WeatherConditionParameters) Validate() error {
	if p.ApiId == nil || len(*p.ApiId) < 1 {
		tag := util.FindFieldTagWithDefault(&p, &p.ApiId, "json", "appid")
		return fmt.Errorf("missing required path parameter '%s'", tag)
	}
	if p.Latitude == nil {
		tag := util.FindFieldTagWithDefault(&p, &p.Latitude, "json", "lat")
		return fmt.Errorf("missing required path parameter '%s'", tag)
	}
	if p.Longitude == nil {
		tag := util.FindFieldTagWithDefault(&p, &p.Longitude, "json", "lon")
		return fmt.Errorf("missing required path parameter '%s'", tag)
	}
	return nil
}

func (c *WeatherWebAppScope) GetWeatherDataHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	openWeatherMap, params := weather.OpenWeatherMap{}, WeatherConditionParameters{}
	if err := chttp.DecodeQueryString(r, &params); err != nil {
		chttp.RespondError(w, http.StatusBadRequest, err)
		return
	}
	if err := params.Validate(); err != nil {
		chttp.RespondError(w, http.StatusInternalServerError, err)
		return
	}
	resp, err := openWeatherMap.GetWeatherCondition(ctx, *params.Latitude, *params.Longitude, *params.ApiId)
	if err != nil {
		chttp.RespondError(w, http.StatusInternalServerError, err)
		return
	}
	data, err := json.Marshal(resp)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("error: %v", err))) // nolint
		return
	}
	w.Header().Set("Content-Type", "application/json")
	if _, err := w.Write(data); err != nil { // failed to write response
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
}
