// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package model

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Health Simple Health Check
type Health struct {
	Ok *bool `json:"ok,omitempty"`
}

// OpenWeatherMapParametersGetCurrentData Open Weather API Parameters for Get Weather Data
type OpenWeatherMapParametersGetCurrentData struct {
	AppId     *string  `json:"appid"`
	Language  *string  `json:"lang"`
	Latitude  *float64 `json:"lat"`
	Longitude *float64 `json:"lat"`
	Mode      *string  `json:"mode"`
	Units     *string  `json:"units"`
}

// OpenWeatherMapResponse Open Weather API Response to GET Current Data: https://api.openweathermap.org/data/2.5/weather.
type OpenWeatherMapResponse struct {
	Base string `json:"base"`

	// Clouds Open Weather API Clouds Data.
	Clouds OpenWeatherMapResponseClouds `json:"Clouds"`
	Cod    int64                        `json:"cod"`

	// Coordinates Open Weather API Coordinates Data.
	Coordinates OpenWeatherMapResponseCoordinates `json:"Coordinates"`
	Id          int64                             `json:"id"`

	// Main Open Weather API Main Data.
	Main OpenWeatherMapResponseMain `json:"Main"`
	Name string                     `json:"name"`

	// Rain Open Weather API Rain Data.
	Rain *OpenWeatherMapResponseRain `json:"Rain,omitempty"`

	// Snow Open Weather API Snow Data.
	Snow *OpenWeatherMapResponseSnow `json:"Snow,omitempty"`

	// System Open Weather API System Data.
	System     OpenWeatherMapResponseSystem `json:"System"`
	TimeData   float64                      `json:"dt"`
	TimeZone   *int64                       `json:"timezone"`
	Visibility float64                      `json:"visibility"`

	// Weather Open Weather API Weather Data.
	Weather OpenWeatherMapResponseWeather `json:"Weather"`

	// Wind Open Weather API Wind Data.
	Wind OpenWeatherMapResponseWind `json:"Wind"`
}

// OpenWeatherMapResponseClouds Open Weather API Clouds Data.
type OpenWeatherMapResponseClouds struct {
	CloudinessPercent float64 `json:"all"`
}

// OpenWeatherMapResponseCoordinates Open Weather API Coordinates Data.
type OpenWeatherMapResponseCoordinates struct {
	Latitude  float64 `json:"lat"`
	Longitude float64 `json:"lon"`
}

// OpenWeatherMapResponseMain Open Weather API Main Data.
type OpenWeatherMapResponseMain struct {
	FeelsLike      float64 `json:"feels_like"`
	GroundLevel    float64 `json:"grnd_level"`
	Humidity       float64 `json:"humidity"`
	Pressure       float64 `json:"pressure"`
	SeaLevel       float64 `json:"sea_level"`
	Temperature    float64 `json:"temp"`
	TemperatureMax float64 `json:"temp_max"`
	TemperatureMin float64 `json:"temp_min"`
}

// OpenWeatherMapResponseRain Open Weather API Rain Data.
type OpenWeatherMapResponseRain struct {
	Volume1Hour float64 `json:"1h"`
	Volume3Hour float64 `json:"3h"`
}

// OpenWeatherMapResponseSnow Open Weather API Snow Data.
type OpenWeatherMapResponseSnow struct {
	Volume1Hour float64 `json:"1h"`
	Volume3Hour float64 `json:"3h"`
}

// OpenWeatherMapResponseSystem Open Weather API System Data.
type OpenWeatherMapResponseSystem struct {
	Country string `json:"country"`
	Id      int64  `json:"id"`
	Message string `json:"message"`
	Sunrise int64  `json:"sunrise"`
	Sunset  int64  `json:"sunset"`
	Type    int64  `json:"type"`
}

// OpenWeatherMapResponseWeather Open Weather API Weather Data.
type OpenWeatherMapResponseWeather struct {
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Id          int64  `json:"id"`
	Main        string `json:"main"`
}

// OpenWeatherMapResponseWind Open Weather API Wind Data.
type OpenWeatherMapResponseWind struct {
	Gust                 float64 `json:"gust"`
	Speed                float64 `json:"speed"`
	WindDirectionDegrees float64 `json:"deg"`
}

// WeatherConditionGetParameters Weather Web App Parameters for Get Weather Data
type WeatherConditionGetParameters struct {
	AppId     string  `json:"appid"`
	Latitude  float64 `json:"lat"`
	Longitude float64 `json:"lat"`
}

// WeatherConditionGetResponse Weather Web App Parameters for Get Weather Data
type WeatherConditionGetResponse struct {
	City                 string `json:"city"`
	OutsideCondition     string `json:"outside_condition"`
	Temperature          string `json:"temperature"`
	TemperatureCondition string `json:"temperature_condition"`
}

// GetV1WeatherDataParams defines parameters for GetV1WeatherData.
type GetV1WeatherDataParams struct {
	// Lat Latitude to get weather conditions for.
	Lat float64 `form:"lat" json:"lat"`

	// Lon Longitude to get weather conditions for.
	Lon float64 `form:"lon" json:"lon"`

	// Appid API ID to Open Weather API.
	Appid string `form:"appid" json:"appid"`
}
