openapi: '3.0.2'
info:
  title: CLesnar Go Models
  description: Common Data Models
  version: 0.1.0
servers:
  - url: http:localhost:8111
security:
  - BearerAuth: []
  - ApiKeyAuth: []
paths:
  /health:
    $ref: ./paths/Health.yml
  /v1/weather/data:
    $ref: ./paths/weather/WeatherConditionGet.yml
components:
  securitySchemas:
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Health:
      $ref: ./schemas/Health.yml
    OpenWeatherMapParametersGetCurrentData: 
      $ref: ./schemas/weather/OpenWeatherMapParametersGetCurrentData.yml
    OpenWeatherMapResponse: 
      $ref: ./schemas/weather/OpenWeatherMapResponse.yml
    OpenWeatherMapResponseClouds: 
      $ref: ./schemas/weather/OpenWeatherMapResponseClouds.yml
    OpenWeatherMapResponseCoordinates: 
      $ref: ./schemas/weather/OpenWeatherMapResponseCoordinates.yml
    OpenWeatherMapResponseMain: 
      $ref: ./schemas/weather/OpenWeatherMapResponseMain.yml
    OpenWeatherMapResponseRain: 
      $ref: ./schemas/weather/OpenWeatherMapResponseRain.yml
    OpenWeatherMapResponseSnow: 
      $ref: ./schemas/weather/OpenWeatherMapResponseSnow.yml
    OpenWeatherMapResponseSystem: 
      $ref: ./schemas/weather/OpenWeatherMapResponseSystem.yml
    OpenWeatherMapResponseWeather: 
      $ref: ./schemas/weather/OpenWeatherMapResponseWeather.yml
    OpenWeatherMapResponseWind: 
      $ref: ./schemas/weather/OpenWeatherMapResponseWind.yml
    WeatherConditionGetParameters: 
      $ref: ./schemas/weather/WeatherConditionGetParameters.yml
    WeatherConditionGetResponse: 
      $ref: ./schemas/weather/WeatherConditionGetResponse.yml
